# Red Wine Dataset 

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

--2021-09-04 15:46:25--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84199 (82K) [application/x-httpd-php]
Saving to: ‘winequality-red.csv’

winequality-red.csv 100%[===================>]  82.23K  --.-KB/s    in 0.02s   

2021-09-04 15:46:25 (3.67 MB/s) - ‘winequality-red.csv’ saved [84199/84199]



In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv("winequality-red.csv",sep=";")
print(dataset)

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.6

In [ ]:
#Reading the dataset and storing it as 2d numpy matrix
XY=np.array(dataset,dtype=float)
print(XY)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
#Apply the following matrix operations (independently to the source matrix of size 1599*12) to the dataset matrix (Use built in functions using different libraries)
#print the shape of the matrix
print("The shape of the matrix is: ",np.shape(XY))

The shape of the matrix is:  (1599, 12)


In [ ]:
#Flatten the matrix
XY.flatten()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.66, 11.  ,  6.  ])

In [ ]:
#slice the matix Separate the features (1599*11 matrix: all columns except the last one) of the dataset and target variable (1599*1 matrix: last column) i.e. quality of wine.
features=XY[:,:-1]
wine_quality=XY[:,-1:]
print("Shape of the features: ",features.shape)
print("Shape of the quality of wine: ",wine_quality.shape)

Shape of the features:  (1599, 11)
Shape of the quality of wine:  (1599, 1)


In [ ]:
#slice the matrix(row slicilng):Divide the matrix XY into two equal sections of size 800*12 each.
half1=XY[0:800]
half2=XY[799:]
print("First half of XY: ",half1.shape)
print("Second half of XY",half2.shape)

First half of XY:  (800, 12)
Second half of XY (800, 12)


In [ ]:
#Shuffle the rows of the matrix XY
np.take(XY,np.random.permutation(XY.shape[0]),axis=0,out=XY)

array([[ 7.9  ,  0.35 ,  0.46 , ...,  0.86 , 12.8  ,  8.   ],
       [ 6.9  ,  0.54 ,  0.3  , ...,  1.18 , 10.5  ,  6.   ],
       [ 7.2  ,  0.66 ,  0.03 , ...,  0.57 ,  9.7  ,  5.   ],
       ...,
       [ 7.8  ,  0.63 ,  0.48 , ...,  0.62 ,  9.5  ,  5.   ],
       [ 7.7  ,  0.705,  0.1  , ...,  0.49 ,  9.7  ,  5.   ],
       [ 7.2  ,  0.38 ,  0.38 , ...,  0.72 , 12.9  ,  7.   ]])

In [ ]:
#Transpose the matrix XY and print the shape
x=XY.transpose()
print(x)

[[ 7.9    6.9    7.2   ...  7.8    7.7    7.2  ]
 [ 0.35   0.54   0.66  ...  0.63   0.705  0.38 ]
 [ 0.46   0.3    0.03  ...  0.48   0.1    0.38 ]
 ...
 [ 0.86   1.18   0.57  ...  0.62   0.49   0.72 ]
 [12.8   10.5    9.7   ...  9.5    9.7   12.9  ]
 [ 8.     6.     5.    ...  5.     5.     7.   ]]


In [ ]:
print(x.shape[0])
print(x.shape[1])

12
1599


In [ ]:
#Inverse the matrix XY and print the shape
np.linalg.pinv(XY)

array([[-5.68279566e-04, -8.58977990e-04,  8.78093613e-04, ...,
        -1.08022187e-03,  5.11205935e-05, -7.56929798e-04],
       [ 2.49994298e-03,  2.77513621e-03, -2.96236911e-03, ...,
         6.31319385e-03,  1.50761833e-03,  1.40922475e-03],
       [ 4.66702610e-03,  6.44722360e-04, -6.70304609e-03, ...,
         1.18992181e-02, -9.50360701e-04,  4.40085578e-03],
       ...,
       [ 2.03386371e-03,  1.49664820e-02, -8.08545668e-04, ...,
        -1.02673851e-03, -2.36359326e-03, -3.95774941e-04],
       [ 4.66184860e-04, -1.00106398e-05, -2.38219704e-04, ...,
        -3.40854857e-04, -3.45661419e-04,  1.11624785e-03],
       [ 1.92649351e-03,  1.46317125e-04, -1.77136612e-05, ...,
        -4.88725879e-05, -1.68658195e-04,  5.68112439e-04]])

In [ ]:
#Compute the determinant of the matrix XY.
X=np.random.randint(20,100,(1599,1599))
np.linalg.slogdet(X)

(1.0, 10124.91659228979)

In [ ]:
#Create a random matrix of size 1599*12 named RXY and perform the following matrix level operations
RXY=np.random.randint(20,50,size=(1599,12))
print(RXY)

[[25 21 43 ... 25 34 37]
 [24 32 49 ... 39 45 47]
 [32 24 37 ... 31 31 33]
 ...
 [24 27 46 ... 27 41 40]
 [33 30 23 ... 24 36 31]
 [23 22 35 ... 24 42 39]]


In [ ]:
#Add XY and RXY
np.add(XY,RXY)

array([[32.9  , 21.35 , 43.46 , ..., 25.86 , 46.8  , 45.   ],
       [30.9  , 32.54 , 49.3  , ..., 40.18 , 55.5  , 53.   ],
       [39.2  , 24.66 , 37.03 , ..., 31.57 , 40.7  , 38.   ],
       ...,
       [31.8  , 27.63 , 46.48 , ..., 27.62 , 50.5  , 45.   ],
       [40.7  , 30.705, 23.1  , ..., 24.49 , 45.7  , 36.   ],
       [30.2  , 22.38 , 35.38 , ..., 24.72 , 54.9  , 46.   ]])

In [ ]:
#Subtract RXY from XY
np.subtract(XY,RXY)

array([[-17.1  , -20.65 , -42.54 , ..., -24.14 , -21.2  , -29.   ],
       [-17.1  , -31.46 , -48.7  , ..., -37.82 , -34.5  , -41.   ],
       [-24.8  , -23.34 , -36.97 , ..., -30.43 , -21.3  , -28.   ],
       ...,
       [-16.2  , -26.37 , -45.52 , ..., -26.38 , -31.5  , -35.   ],
       [-25.3  , -29.295, -22.9  , ..., -23.51 , -26.3  , -26.   ],
       [-15.8  , -21.62 , -34.62 , ..., -23.28 , -29.1  , -32.   ]])

In [ ]:
#Outer product between XY and RXY
np.outer(XY,RXY)

array([[197.5 , 165.9 , 339.7 , ..., 189.6 , 331.8 , 308.1 ],
       [  8.75,   7.35,  15.05, ...,   8.4 ,  14.7 ,  13.65],
       [ 11.5 ,   9.66,  19.78, ...,  11.04,  19.32,  17.94],
       ...,
       [ 18.  ,  15.12,  30.96, ...,  17.28,  30.24,  28.08],
       [322.5 , 270.9 , 554.7 , ..., 309.6 , 541.8 , 503.1 ],
       [175.  , 147.  , 301.  , ..., 168.  , 294.  , 273.  ]])

In [ ]:
print(np.outer(XY,RXY).shape)

(19188, 19188)


In [ ]:
#Create a random matrix of size 12*1 named RXY2 and perform the inner product between XY and RXY2 (i.e. dot product between 1599*12 and 12*1). Print the matrix as well as its shape.
RXY2=np.random.randint(20,50,size=(12,1))
print(RXY2)

[[48]
 [23]
 [41]
 [26]
 [35]
 [31]
 [42]
 [26]
 [40]
 [35]
 [26]
 [39]]


In [ ]:
print(RXY2.shape)

(12, 1)


In [ ]:
np.dot(XY,RXY2)

array([[3356.2698 ],
       [5809.4285 ],
       [5166.82318],
       ...,
       [5539.4686 ],
       [2457.3426 ],
       [3715.13256]])

In [ ]:
print(np.dot(XY,RXY2).shape)

(1599, 1)


#Mnist dataset

In [ ]:
data=pd.read_csv('./sample_data/mnist_train_small.csv')
print(data)

       6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0      5  0    0    0    0    0  ...      0      0      0      0      0      0
1      7  0    0    0    0    0  ...      0      0      0      0      0      0
2      9  0    0    0    0    0  ...      0      0      0      0      0      0
3      5  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
19994  0  0    0    0    0    0  ...      0      0      0      0      0      0
19995  1  0    0    0    0    0  ...      0      0      0      0      0      0
19996  2  0    0    0    0    0  ...      0      0      0      0      0      0
19997  9  0    0    0    0    0  ...      0      0      0      0      0      0
19998  5  0    0    0    0    0  ...      0      0      0      0      0      0

[19999 rows x 785 columns]


In [ ]:
XY=np.array(data)
print(XY)


[[5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]


In [ ]:
#Apply the following matrix operations (independently to the source matrix of size 1599*12) to the dataset matrix (Use built in functions using different libraries)
#Print shape of the matrix XY.
print("The shape of the matrix is: ",XY.shape)

The shape of the matrix is:  (19999, 785)


In [ ]:
#Flatten the matrix XY into a 1D array
XY.flatten()


array([5, 0, 0, ..., 0, 0, 0])

In [ ]:
#Slice the matrix (column slicing): Separate the features (1599*11 matrix: all columns except the last one) of the dataset and target variable (1599*1 matrix: last column) i.e. quality of wine.
features=XY[:,:-1]
target=XY[:,-1:]
print(features.shape)
print(target.shape)

(19999, 784)
(19999, 1)


In [ ]:
#Slice the matrix (row slicing): Divide the matrix XY into two equal sections 
x=XY[0:10000]
y=XY[9999:]
print(x.shape)
print(y.shape)

(10000, 785)
(10000, 785)


In [ ]:
#Shuffle the rows of the matrix XY
np.take(XY,np.random.permutation(XY.shape[0]),axis=0,out=XY)

array([[7, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [8, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0]])

In [ ]:
#Transpose the matrix XY and print the shape
np.transpose(XY)

array([[7, 0, 6, ..., 8, 5, 6],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#Inverse the matrix XY and print the shape
np.linalg.pinv(XY)

array([[ 2.89678750e-05, -2.54602971e-05,  2.39878380e-05, ...,
        -7.25817434e-06,  3.78135361e-05, -1.28175383e-06],
       [-1.67460062e-18,  6.34716682e-16,  7.33218590e-17, ...,
         1.67665301e-16,  2.91200007e-17,  4.16949387e-17],
       [-3.26213544e-18,  3.19659154e-16,  2.77622768e-17, ...,
         8.88007486e-17,  9.61136116e-19,  2.31482305e-17],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
#Compute the determinant of the matrix XY.
X=np.random.randint(30,200,(1900,1900))
np.linalg.slogdet(X)

(-1.0, 13624.108552620864)

In [ ]:
#Create a random matrix of size 1599*12 named RXY and perform the following matrix level operations
RXY=np.random.randint(20,100,(19999,785))
print(RXY)


[[66 82 62 ... 68 29 97]
 [77 64 90 ... 81 68 80]
 [80 75 59 ... 83 35 62]
 ...
 [26 21 37 ... 57 75 36]
 [66 77 31 ... 25 41 72]
 [54 46 99 ... 49 46 76]]


In [ ]:
#Add XY and RXY
np.add(XY,RXY)

array([[73, 82, 62, ..., 68, 29, 97],
       [77, 64, 90, ..., 81, 68, 80],
       [86, 75, 59, ..., 83, 35, 62],
       ...,
       [34, 21, 37, ..., 57, 75, 36],
       [71, 77, 31, ..., 25, 41, 72],
       [60, 46, 99, ..., 49, 46, 76]])

In [ ]:
#Subtract RXY from XY
np.subtract(XY,RXY)

array([[-59, -82, -62, ..., -68, -29, -97],
       [-77, -64, -90, ..., -81, -68, -80],
       [-74, -75, -59, ..., -83, -35, -62],
       ...,
       [-18, -21, -37, ..., -57, -75, -36],
       [-61, -77, -31, ..., -25, -41, -72],
       [-48, -46, -99, ..., -49, -46, -76]])

In [ ]:
#Create a random matrix of size 12*1 named RXY2 and perform the inner product between XY and RXY2 (i.e. dot product between 1599*12 and 12*1). Print the matrix as well as its shape.
RXY2=np.random.randint(20,150,(12,1))
print(RXY2)

[[147]
 [ 69]
 [ 88]
 [ 68]
 [122]
 [146]
 [142]
 [ 96]
 [117]
 [ 58]
 [133]
 [ 60]]


In [ ]:
print(RXY2.shape)

(12, 1)
