In [29]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import r2_score, mean_squared_error, median_absolute_error,mean_absolute_error,explained_variance_score,max_error
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
import re

In [2]:
!wget "https://raw.githubusercontent.com/ramahanisha-7/Datasets/main/speeddating.csv"

--2021-10-04 05:34:19--  https://raw.githubusercontent.com/ramahanisha-7/Datasets/main/speeddating.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4988096 (4.8M) [text/plain]
Saving to: ‘speeddating.csv’

speeddating.csv     100%[===================>]   4.76M  --.-KB/s    in 0.1s    

2021-10-04 05:34:21 (49.6 MB/s) - ‘speeddating.csv’ saved [4988096/4988096]



In [3]:
data = pd.read_csv("speeddating.csv")
data.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3,10,11,15,16,17,18,19,39,40,41,42,43,44,51,52,53,54,55,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,107,109) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


has_null  wave  gender age  ... met  decision decision_o match
0         0     1  female  21  ...   0         1          0     0
1         0     1  female  21  ...   1         1          0     0
2         1     1  female  21  ...   1         1          1     1
3         0     1  female  21  ...   0         1          1     1
4         0     1  female  21  ...   0         1          1     1

[5 rows x 123 columns]

In [4]:
dummy=pd.get_dummies(data.gender)
dummy

female  male
0          1     0
1          1     0
2          1     0
3          1     0
4          1     0
...      ...   ...
8373       0     1
8374       0     1
8375       0     1
8376       0     1
8377       0     1

[8378 rows x 2 columns]

In [6]:
data = pd.concat([data,dummy], axis=1)
data.drop('gender', axis=1, inplace=True)
data

has_null  wave age age_o  d_age  ... match  female male  female male
0            0     1  21    27      6  ...     0       1    0       1    0
1            0     1  21    22      1  ...     0       1    0       1    0
2            1     1  21    22      1  ...     1       1    0       1    0
3            0     1  21    23      2  ...     1       1    0       1    0
4            0     1  21    24      3  ...     1       1    0       1    0
...        ...   ...  ..   ...    ...  ...   ...     ...  ...     ...  ...
8373         1    21  25    26      1  ...     0       0    1       0    1
8374         1    21  25    24      1  ...     0       0    1       0    1
8375         1    21  25    29      4  ...     0       0    1       0    1
8376         1    21  25    22      3  ...     0       0    1       0    1
8377         1    21  25    22      3  ...     0       0    1       0    1

[8378 rows x 126 columns]

In [7]:
data.head()

has_null  wave age age_o  d_age  ... match  female male  female male
0         0     1  21    27      6  ...     0       1    0       1    0
1         0     1  21    22      1  ...     0       1    0       1    0
2         1     1  21    22      1  ...     1       1    0       1    0
3         0     1  21    23      2  ...     1       1    0       1    0
4         0     1  21    24      3  ...     1       1    0       1    0

[5 rows x 126 columns]

In [8]:
list=[]
cols=data.columns[5:6].tolist()+data.columns[11:13].tolist()+data.columns[20:26].tolist() + data.columns[32:37].tolist()+data.columns[45:50].tolist()
for col in cols:
  for i in range(data.shape[0]):
    list.append(re.findall('\d+', data[col][i]))
    data[col][i]=int((int(list[i][0])+int(list[i][1]))/2)
  list.clear()
data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


has_null  wave age age_o  d_age  ... match  female male  female male
0            0     1  21    27      6  ...     0       1    0       1    0
1            0     1  21    22      1  ...     0       1    0       1    0
2            1     1  21    22      1  ...     1       1    0       1    0
3            0     1  21    23      2  ...     1       1    0       1    0
4            0     1  21    24      3  ...     1       1    0       1    0
...        ...   ...  ..   ...    ...  ...   ...     ...  ...     ...  ...
8373         1    21  25    26      1  ...     0       0    1       0    1
8374         1    21  25    24      1  ...     0       0    1       0    1
8375         1    21  25    29      4  ...     0       0    1       0    1
8376         1    21  25    22      3  ...     0       0    1       0    1
8377         1    21  25    22      3  ...     0       0    1       0    1

[8378 rows x 126 columns]

In [9]:
dropcols=["d_shared_interests_o","d_sports","d_tvsports","d_exercise","d_dining","d_museums","d_art","d_hiking","d_gaming","d_clubbing","d_reading","d_tv","d_theater","d_movies","d_concerts","d_music","d_shopping","d_yoga","d_interests_correlate","d_expected_happy_with_sd_people","d_expected_num_interested_in_me","d_expected_num_matches","d_like","d_guess_prob_liked","d_attractive_partner","d_sincere_partner","d_intelligence_partner","d_funny_partner","d_ambition_partner","d_shared_interests_partner"]
data=data.drop(dropcols,axis=1)

In [10]:
multi_hot = MultiLabelBinarizer()
data["race"]=multi_hot.fit_transform(data["race"])
data["race_o"]=multi_hot.fit_transform(data["race_o"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
data.head()

has_null  wave age age_o  d_age  ... match  female male  female male
0         0     1  21    27      6  ...     0       1    0       1    0
1         0     1  21    22      1  ...     0       1    0       1    0
2         1     1  21    22      1  ...     1       1    0       1    0
3         0     1  21    23      2  ...     1       1    0       1    0
4         0     1  21    24      3  ...     1       1    0       1    0

[5 rows x 96 columns]

In [49]:
x=pd.concat([data.iloc[:,0:91],data.iloc[:,92:]],axis=1)
y=data.iloc[:,91:92]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=41)

In [14]:
X_train=X_train.select_dtypes(exclude=['object'])
X_test=X_test.select_dtypes(exclude=['object'])

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5864, 12)
(2514, 12)
(5864, 1)
(2514, 1)


In [16]:
model=DecisionTreeClassifier(random_state=0).fit(X_train,y_train)
model

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [17]:
confusion_matrix(y_test, model.predict(X_test))
precision_score(y_test, model.predict(X_test), average='macro')
recall_score(y_test, model.predict(X_test), average='micro')

1.0

In [18]:
model=DecisionTreeClassifier(criterion="entropy",splitter="random",max_depth=5 ,min_samples_split=3,min_weight_fraction_leaf=0.3,max_features="sqrt").fit(X_train,y_train)
model

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.3, presort='deprecated',
                       random_state=None, splitter='random')

In [19]:
print(confusion_matrix(y_test, model.predict(X_test)))
print(precision_score(y_test, model.predict(X_test), average='macro'))
print(recall_score(y_test, model.predict(X_test), average='micro'))

[[2101    0]
 [ 413    0]]
0.417859984089101
0.835719968178202


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
model = LogisticRegression(random_state=0).fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [34]:
y_pred = model.predict(X_train)

In [35]:
test_accuracy_sklearn = accuracy_score(y_train, y_pred)

print(f"\nAccuracy on testing set: {test_accuracy_sklearn}")


Accuracy on testing set: 1.0


In [36]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4897
           1       1.00      1.00      1.00       967

    accuracy                           1.00      5864
   macro avg       1.00      1.00      1.00      5864
weighted avg       1.00      1.00      1.00      5864



In [38]:
confusion_matrix(y_train, y_pred)

array([[4897,    0],
       [   0,  967]])

In [40]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_train, y_pred)

(array([1., 1.]), array([1., 1.]), array([1., 1.]), array([4897,  967]))

# Linear Regession Model

In [41]:
!wget "https://raw.githubusercontent.com/ramahanisha-7/Datasets/main/Dataset%20File.csv"

--2021-10-04 05:55:26--  https://raw.githubusercontent.com/ramahanisha-7/Datasets/main/Dataset%20File.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2326 (2.3K) [text/plain]
Saving to: ‘Dataset File.csv’

Dataset File.csv    100%[===================>]   2.27K  --.-KB/s    in 0s      

2021-10-04 05:55:27 (32.1 MB/s) - ‘Dataset File.csv’ saved [2326/2326]



In [43]:
data = pd.read_csv("Dataset File.csv")
data.head()

G2  G3
0  30  30
1  25  30
2  40  50
3  70  75
4  50  50

In [51]:
df = np.array(data[:])
X = df[:,:-1]
y = df[:,-1:]

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [53]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
regressor = DecisionTreeRegressor(random_state=0).fit(X_train,y_train)
cross_val_score(regressor, X, y, cv=10)

array([0.86905993, 0.84232055, 0.93182866, 0.86331068, 0.79735803,
       0.8289487 , 0.76015031, 0.66992416, 0.58482293, 0.8506774 ])